//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class workshopEntities : DbContext
{
    public workshopEntities()
        : base("name=workshopEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<car> cars { get; set; }
    public virtual DbSet<client> clients { get; set; }
    public virtual DbSet<colorofcar> colorofcars { get; set; }
    public virtual DbSet<detail> details { get; set; }
    public virtual DbSet<markofcar> markofcars { get; set; }
    public virtual DbSet<modelofcar> modelofcars { get; set; }
    public virtual DbSet<operation> operations { get; set; }
    public virtual DbSet<order> orders { get; set; }
    public virtual DbSet<photo> photos { get; set; }
    public virtual DbSet<process> processes { get; set; }
    public virtual DbSet<process_has_detail> process_has_detail { get; set; }
    public virtual DbSet<standartdetail> standartdetails { get; set; }
    public virtual DbSet<worker> workers { get; set; }
    public virtual DbSet<workerhasskill> workerhasskills { get; set; }
}
