//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class car
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public car()
    {
        this.details = new HashSet<detail>();
        this.orders = new HashSet<order>();
    }

    public int idCar { get; set; }
    public string vincod { get; set; }
    public string registrNumber { get; set; }
    public int ModelOfCar_idModelOfCar { get; set; }
    public int ColorOfCar_idColorOfCar { get; set; }
    public int Client_idClient { get; set; }

    public virtual client client { get; set; }
    public virtual colorofcar colorofcar { get; set; }
    public virtual modelofcar modelofcar { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<detail> details { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<order> orders { get; set; }
}

public partial class client
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public client()
    {
        this.cars = new HashSet<car>();
    }

    public int idClient { get; set; }
    public string firstName { get; set; }
    public string middleName { get; set; }
    public string lastName { get; set; }
    public string phone { get; set; }
    public string email { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<car> cars { get; set; }
}

public partial class colorofcar
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public colorofcar()
    {
        this.cars = new HashSet<car>();
    }

    public int idColorOfCar { get; set; }
    public string nameColorOfCar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<car> cars { get; set; }
}

public partial class detail
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public detail()
    {
        this.process_has_detail = new HashSet<process_has_detail>();
    }

    public int idDetail { get; set; }
    public int StandartDetail_idStandartDetail { get; set; }
    public int Car_idCar { get; set; }

    public virtual car car { get; set; }
    public virtual standartdetail standartdetail { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<process_has_detail> process_has_detail { get; set; }
}

public partial class markofcar
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public markofcar()
    {
        this.modelofcars = new HashSet<modelofcar>();
    }

    public int idMarkOfCar { get; set; }
    public string nameMarkOfCar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<modelofcar> modelofcars { get; set; }
}

public partial class modelofcar
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public modelofcar()
    {
        this.cars = new HashSet<car>();
    }

    public int idModelOfCar { get; set; }
    public string nameModelOfCar { get; set; }
    public int MarkOfCar_idMarkOfCar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<car> cars { get; set; }
    public virtual markofcar markofcar { get; set; }
}

public partial class operation
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public operation()
    {
        this.processes = new HashSet<process>();
        this.workerhasskills = new HashSet<workerhasskill>();
    }

    public int idOperation { get; set; }
    public string nameOperation { get; set; }
    public Nullable<System.TimeSpan> duration { get; set; }
    public string Color { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<process> processes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<workerhasskill> workerhasskills { get; set; }
}

public partial class order
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public order()
    {
        this.photos = new HashSet<photo>();
        this.processes = new HashSet<process>();
    }

    public int idOrder { get; set; }
    public Nullable<System.DateTime> dateTime { get; set; }
    public Nullable<bool> status { get; set; }
    public int Worker_idWorker { get; set; }
    public int Car_idCar { get; set; }

    public virtual car car { get; set; }
    public virtual worker worker { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<photo> photos { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<process> processes { get; set; }
}

public partial class photo
{
    public int idPhoto { get; set; }
    public byte[] image { get; set; }
    public string notes { get; set; }
    public Nullable<System.DateTime> dateTime { get; set; }
    public int Order_idOrder { get; set; }

    public virtual order order { get; set; }
}

public partial class process
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public process()
    {
        this.process_has_detail = new HashSet<process_has_detail>();
    }

    public int idProcess { get; set; }
    public Nullable<System.DateTime> dateTimeStart { get; set; }
    public Nullable<System.DateTime> dateTimeFinish { get; set; }
    public Nullable<System.DateTime> dateTimeStartFact { get; set; }
    public Nullable<System.DateTime> dateTimeFinishFact { get; set; }
    public int Worker_idWorker { get; set; }
    public int Operation_idOperation { get; set; }
    public int Order_idOrder { get; set; }

    public virtual operation operation { get; set; }
    public virtual order order { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<process_has_detail> process_has_detail { get; set; }
    public virtual worker worker { get; set; }
}

public partial class process_has_detail
{
    public int idProcess_has_Detail { get; set; }
    public int Process_idProcess { get; set; }
    public int Detail_idDetail { get; set; }

    public virtual detail detail { get; set; }
    public virtual process process { get; set; }
}

public partial class standartdetail
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public standartdetail()
    {
        this.details = new HashSet<detail>();
    }

    public int idStandartDetail { get; set; }
    public string nameStandartDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<detail> details { get; set; }
}

public partial class worker
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public worker()
    {
        this.orders = new HashSet<order>();
        this.processes = new HashSet<process>();
        this.workerhasskills = new HashSet<workerhasskill>();
    }

    public int idWorker { get; set; }
    public string firstName { get; set; }
    public string middleName { get; set; }
    public string lastName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<order> orders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<process> processes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<workerhasskill> workerhasskills { get; set; }
}

public partial class workerhasskill
{
    public int idWorkerHasSkill { get; set; }
    public Nullable<int> level { get; set; }
    public int Worker_idWorker { get; set; }
    public int Operation_idOperation { get; set; }

    public virtual operation operation { get; set; }
    public virtual worker worker { get; set; }
}
